function skillsMember() {
    return [
        'HTML',
        'CSS',
        'JavaScript',
        'Node.js',
        'React.js',
        'SQL',
        'NoSQL',
        'Java',
        'Python',
        'C#',
        'C++',
        'Ruby',
        'PHP',
        'Docker',
        'Kubernetes',
        'Git',
        'CI/CD',
        'AWS',
        'Azure',
        'GCP',
        'DevOps',
        'Agile',
        'Scrum',
        'Kanban',
        'TDD',
        'BDD',
        'DDD',
        'Microservices',
        'GraphQL',
        'REST',
        'SOA',
        'Linux',
        'Windows',
        'MacOS',
        'Android',
        'iOS',
        'Flutter',
        'Swift',
        'Kotlin',
        'Angular',
        'Vue.js',
        'Svelte',
        'Jest',
        'Mocha',
        'Cypress',
        'Jasmine',
        'Enzyme',
        'Puppeteer',
        'Playwright',
        'Express.js',
        'Next.js',
        'Gatsby.js',
        'Nest.js',
        'Spring',
        'Hibernate',
        'JPA',
        'ASP.NET',
        'ASP.NET Core',
        'Ruby on Rails',
        'Laravel',
        'Django',
        'Flask',
        'CI/CD',
        'Jenkins',
        'Travis CI',
        'Circle CI',
        'GitHub Actions',
        'Bitbucket Pipelines',
        'GitLab CI',
        'AWS CodePipeline',
        'Azure DevOps',
        'Google Cloud Build',
        'Docker',
        'Kubernetes',
        'Helm',
        'Terraform',
        'Ansible',
        'Puppet',
        'Chef',
        'AWS CloudFormation',
        'Azure Resource Manager',
        'Google Cloud Deployment Manager',
        'AWS',
        'Azure',
        'Google Cloud',
        'DigitalOcean',
        'Heroku',
        'Netlify',
        'Vercel',
        'Firebase',
        'MongoDB',
        'Couchbase',
        'Cassandra',
        'CouchDB',
        'Neo4j',
        'Redis',
        'MariaDB',
        'MySQL',
        'PostgreSQL',
        'SQLite']
}